/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Component;

import BLL.UsersBLL;
import DTO.UsersDTO;
import UI.JPanelLoader;
import UI.MainFrame;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    
    private boolean isShowPassword = false;
    JPanelLoader jPanelLoader = new JPanelLoader();
    
    JFrame jFrameAuth;
    JPanel jPanelAuth;
    
    public Login() {
        initComponents();
        setIcon();
    }
    
    public Login(JFrame jFrameAuth, JPanel jPanelAuth) {
        initComponents();
        setIcon();
        this.jFrameAuth = jFrameAuth;
        this.jPanelAuth = jPanelAuth;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLinkToRegister = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jCheckBoxRememberPassword = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelLinkToForgotPassword = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelUserIcon = new javax.swing.JLabel();
        jLabelShowPasswordIcon = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabelLinkToRegister.setForeground(new java.awt.Color(51, 51, 255));
        jLabelLinkToRegister.setText("<html><u>Đăng ký ngay!</u></html>");
        jLabelLinkToRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelLinkToRegisterMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ĐĂNG NHẬP");

        jLabel5.setText("Mật khẩu");

        jButtonLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLogin.setText("Đăng nhập");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jCheckBoxRememberPassword.setText("Nhớ mật khẩu");

        jLabel4.setText("Tên đăng nhập");

        jLabelLinkToForgotPassword.setForeground(new java.awt.Color(255, 0, 0));
        jLabelLinkToForgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLinkToForgotPassword.setText("Quên mật khẩu?");

        jLabel6.setText("Bạn chưa có tài khoản?");

        jLabelShowPasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelShowPasswordIconMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelShowPasswordIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBoxRememberPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLinkToForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(jLabelLinkToRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelShowPasswordIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jPasswordField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxRememberPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLinkToForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelLinkToRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setIcon() {
        ImageIcon user = new ImageIcon(getClass().getResource("/icon/user.png"));
        Image imgUser = user.getImage();
        Image scaledImgUser = imgUser.getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        jLabelUserIcon.setIcon(new ImageIcon(scaledImgUser));     
        
        ImageIcon hidden = new ImageIcon(getClass().getResource("/icon/hidden.png"));
        Image imgHidden = hidden.getImage();
        Image scaledImgHidden = imgHidden.getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        jLabelShowPasswordIcon.setIcon(new ImageIcon(scaledImgHidden));
    }
    
    private void jLabelShowPasswordIconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelShowPasswordIconMouseReleased
        if(isShowPassword) {
            ImageIcon hidden = new ImageIcon(getClass().getResource("/icon/hidden.png"));
            Image imgHidden = hidden.getImage();
            Image scaledImgHidden = imgHidden.getScaledInstance(jLabelShowPasswordIcon.getWidth(), jLabelShowPasswordIcon.getHeight(), Image.SCALE_SMOOTH);
            jLabelShowPasswordIcon.setIcon(new ImageIcon(scaledImgHidden));
            isShowPassword = false;
        } else {
            ImageIcon eye = new ImageIcon(getClass().getResource("/icon/eye.png"));
            Image imgEye = eye.getImage();
            Image scaledImgEye = imgEye.getScaledInstance(jLabelShowPasswordIcon.getWidth(), jLabelShowPasswordIcon.getHeight(), Image.SCALE_SMOOTH);
            jLabelShowPasswordIcon.setIcon(new ImageIcon(scaledImgEye));
            isShowPassword = true;
        }
    }//GEN-LAST:event_jLabelShowPasswordIconMouseReleased

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed

    String username = jTextField1.getText();
    String password = new String(jPasswordField1.getPassword());

    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Tên đăng nhập hoặc mật khẩu không được bỏ trống!",
                "Cảnh Báo",
                JOptionPane.WARNING_MESSAGE
        );
    } else {
        UsersDTO user = UsersBLL.authenticateUser(username, password);

        if (user != null) {
            jFrameAuth.setVisible(false);
            MainFrame mainFrame = new MainFrame(user);
            mainFrame.setVisible(true);
        } else {
            // Nếu thông tin đăng nhập không đúng
            JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu sai!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jLabelLinkToRegisterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLinkToRegisterMousePressed
        jFrameAuth.setTitle("Đăng ký");
        Register jPanelRegister = new Register(jFrameAuth, jPanelAuth);
        jPanelLoader.jPanelLoader(jPanelAuth, jPanelRegister);
    }//GEN-LAST:event_jLabelLinkToRegisterMousePressed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JCheckBox jCheckBoxRememberPassword;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelLinkToForgotPassword;
    private javax.swing.JLabel jLabelLinkToRegister;
    private javax.swing.JLabel jLabelShowPasswordIcon;
    private javax.swing.JLabel jLabelUserIcon;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
