/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Component;

import BLL.ExamsBLL;
import BLL.ResultBLL;
import BLL.TestBLL;
import DTO.ExamsDTO;
import DTO.ResultDTO;
import DTO.TestDTO;
import DTO.ThongKeDTO;
import java.util.ArrayList;
import java.util.List;
import java.sql.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Statistical extends javax.swing.JPanel {

    /**
     * Creates new form Statistical
     */
    
    private DefaultTableModel tblModel;
    
    public Statistical() {
        initComponents();
        initTable();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStatistical = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Đến");

        jLabel2.setText("Tên bài thi:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(10, 10, 10))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTableStatistical.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã bài thi", "Tên bài thi", "Số lượt thi", "Đạt", "Rớt", "Ngày thi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableStatistical.setRowHeight(30);
        jTableStatistical.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableStatistical.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableStatistical);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initTable() {
        tblModel = new DefaultTableModel();
        String[] headerTbl = new String[]{"Mã bài thi", "Tên bài thi", "Số lượt thi", "Đạt", "Rớt", "Ngày thi"};
        tblModel.setColumnIdentifiers(headerTbl);
        jTableStatistical.setModel(tblModel);
    }
    
    private void display() {
        TestBLL testBLL = new TestBLL();
        ExamsBLL examBLL = new ExamsBLL();
        ResultBLL resultBLL = new ResultBLL();
        
        List<TestDTO> testList = testBLL.getAllTests();
        List<ExamsDTO> examList = examBLL.getAllExams();
        List<ResultDTO> resultList = resultBLL.getAllResults();
        
        for(ResultDTO result: resultList) {
            for(ExamsDTO exam: examList) {
                if(result.getExCode().equals(exam.getExCode())) {
                    result.setExCode(exam.getTestCode());
                    break;
                }
            }
        }
        
        List<ThongKeDTO> thongKeList = new ArrayList<>();
        for(TestDTO test: testList) {
            ThongKeDTO thongKe = new ThongKeDTO();
            thongKe.setMaBaiThi(test.getTestCode());
            thongKe.setTenBaiThi(test.getTestTitle());
            thongKe.setNgaythi(Date.valueOf(test.getTestDate()));
            
            int dat = 0;
            int luotthi = 0;
            
            for(ResultDTO result: resultList) {
                if(result.getExCode().equals(test.getTestCode())) {
                    luotthi++;
                    if(result.getRsMark() >= 5) {
                        dat++;
                    }
                }
            }
            thongKe.setSoLuotThi(luotthi);
            thongKe.setDat(dat);
            thongKe.setRot(luotthi - dat);
            
            thongKeList.add(thongKe);
            System.out.println(thongKe.toString());
        }
        
        try {
            tblModel.setRowCount(0);
            for (int i = 0; i < thongKeList.size(); i++) {
                tblModel.addRow(new Object[]{
                    thongKeList.get(i).getMaBaiThi(), thongKeList.get(i).getTenBaiThi(), thongKeList.get(i).getSoLuotThi(), thongKeList.get(i).getDat(), thongKeList.get(i).getRot(), thongKeList.get(i).getNgaythi()
                });
            }
        } catch (Exception e) {

        }
    }
    
    private void displayWithCondition(Date begin, Date end, String testTitle) {
        
    }
    
    private void loadData(List<ThongKeDTO> thongKe) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStatistical;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
