/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DTO.UsersDTO;
import UI.Component.ExamManagementUI;
import UI.Component.ExamSelectionUI;
import UI.Component.QuestionManagementUI;
import UI.Component.TestManagementUI;
import UI.Component.TopicsManagement;
import UI.Component.UserManagement;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private final JPanelLoader jPanelLoader = new JPanelLoader();
    private UsersDTO userLogin;
            
    public MainFrame() {
    }
    
    public MainFrame(UsersDTO userLogin) {
        this.userLogin = userLogin;
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setFullNameUser(userLogin.getUserFullName());
        setMenu(userLogin.getIsAdmin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelUserFullName = new javax.swing.JLabel();
        jLabelAvatar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButtonInformation = new javax.swing.JButton();
        jButtonUserManagement = new javax.swing.JButton();
        jButtonStatistical = new javax.swing.JButton();
        jButtonQuestionManagement = new javax.swing.JButton();
        jButtonTopicManagement = new javax.swing.JButton();
        jButtonTestManagement = new javax.swing.JButton();
        jButtonExamManagement = new javax.swing.JButton();
        jButtonTakeTest = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanelFunction = new javax.swing.JPanel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thi trắc nghiệm trực tuyến");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setMinimumSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(249, 249, 249));

        jLabelUserFullName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUserFullName.setText("Nguyễn Đình Thông");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUserFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(249, 249, 249));

        jButtonInformation.setText("Thông tin cá nhân");

        jButtonUserManagement.setText("Người dùng");
        jButtonUserManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonUserManagementMouseReleased(evt);
            }
        });

        jButtonStatistical.setText("Thống kê");
        jButtonStatistical.setToolTipText("");

        jButtonQuestionManagement.setText("Câu hỏi");
        jButtonQuestionManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuestionManagementActionPerformed(evt);
            }
        });

        jButtonTopicManagement.setText("Chủ đề");
        jButtonTopicManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTopicManagementActionPerformed(evt);
            }
        });

        jButtonTestManagement.setText("Bài thi");
        jButtonTestManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestManagementActionPerformed(evt);
            }
        });

        jButtonExamManagement.setText("Đề thi");
        jButtonExamManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExamManagementActionPerformed(evt);
            }
        });

        jButtonTakeTest.setText("Làm bài thi");
        jButtonTakeTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTakeTestActionPerformed(evt);
            }
        });

        jButtonLogout.setText("Đăng xuất");
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTakeTest, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExamManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTestManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTopicManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQuestionManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStatistical, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonTakeTest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonStatistical, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonQuestionManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonTopicManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonTestManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonExamManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanelFunction.setBackground(new java.awt.Color(249, 249, 249));

        jLabelBackground.setMinimumSize(new java.awt.Dimension(730, 573));

        javax.swing.GroupLayout jPanelFunctionLayout = new javax.swing.GroupLayout(jPanelFunction);
        jPanelFunction.setLayout(jPanelFunctionLayout);
        jPanelFunctionLayout.setHorizontalGroup(
            jPanelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFunctionLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanelFunctionLayout.setVerticalGroup(
            jPanelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelFunction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFunction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setFullNameUser(String userFullName) {
        jLabelUserFullName.setText(userFullName);
    }
    
    private void setMenu(byte isAdmin) {
        if(isAdmin == 1) {
            
        } else {
            jButtonUserManagement.setVisible(false);
            jButtonQuestionManagement.setVisible(false);
            jButtonTopicManagement.setVisible(false);
            jButtonTestManagement.setVisible(false);
            jButtonExamManagement.setVisible(false);
            jButtonStatistical.setVisible(false);
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ImageIcon user = new ImageIcon(getClass().getResource("/icon/user.png"));
        Image imgUser = user.getImage();
        Image scaledImgUser = imgUser.getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        jLabelAvatar.setIcon(new ImageIcon(scaledImgUser));
        
        ImageIcon userManagement = new ImageIcon(getClass().getResource("/icon/userManagement.png"));
        Image imgUserManagement = userManagement.getImage();
        Image scaledImgUserManagement = imgUserManagement.getScaledInstance(16, 16, Image.SCALE_SMOOTH);
        jButtonUserManagement.setIcon(new ImageIcon(scaledImgUserManagement));
        
        ImageIcon questionManagement = new ImageIcon(getClass().getResource("/icon/question.png"));
        Image imgQuestionManagement = questionManagement.getImage();
        Image scaledImgQuestionManagement = imgQuestionManagement.getScaledInstance(16, 16, Image.SCALE_SMOOTH);
        jButtonQuestionManagement.setIcon(new ImageIcon(scaledImgQuestionManagement));
        
        ImageIcon topicManagement = new ImageIcon(getClass().getResource("/icon/topic.png"));
        Image imgTopicManagement = topicManagement.getImage();
        Image scaledImgTopicManagement = imgTopicManagement.getScaledInstance(16, 16, Image.SCALE_SMOOTH);
        jButtonTopicManagement.setIcon(new ImageIcon(scaledImgTopicManagement));
        
        ImageIcon testManagement = new ImageIcon(getClass().getResource("/icon/test.png"));
        Image imgTestManagement = testManagement.getImage();
        Image scaledImgTestManagement = imgTestManagement.getScaledInstance(16, 16, Image.SCALE_SMOOTH);
        jButtonTestManagement.setIcon(new ImageIcon(scaledImgTestManagement));
        
        ImageIcon examManagement = new ImageIcon(getClass().getResource("/icon/exam.png"));
        Image imgExamManagement = examManagement.getImage();
        Image scaledImgExamManagement = imgExamManagement.getScaledInstance(16, 16, Image.SCALE_SMOOTH);
        jButtonExamManagement.setIcon(new ImageIcon(scaledImgExamManagement));
        
        ImageIcon statistical = new ImageIcon(getClass().getResource("/icon/statistical.png"));
        Image imgStatistical = statistical.getImage();
        Image scaledStatistical = imgStatistical.getScaledInstance(16, 16, Image.SCALE_SMOOTH);
        jButtonStatistical.setIcon(new ImageIcon(scaledStatistical));
        
        ImageIcon takeTest = new ImageIcon(getClass().getResource("/icon/takeTest.png"));
        Image imgTakeTest = takeTest.getImage();
        Image scaledImgTakeTest = imgTakeTest.getScaledInstance(16, 16, Image.SCALE_SMOOTH);
        jButtonTakeTest.setIcon(new ImageIcon(scaledImgTakeTest));
        
        ImageIcon information = new ImageIcon(getClass().getResource("/icon/information.png"));
        Image imgInformation = information.getImage();
        Image scaledImgInformation = imgInformation.getScaledInstance(16, 16, Image.SCALE_SMOOTH);
        jButtonInformation.setIcon(new ImageIcon(scaledImgInformation));
        
        ImageIcon logout = new ImageIcon(getClass().getResource("/icon/logout.png"));
        Image imgLogout = logout.getImage();
        Image scaledImgLogout = imgLogout.getScaledInstance(16, 16, Image.SCALE_SMOOTH);
        jButtonLogout.setIcon(new ImageIcon(scaledImgLogout));
        
        ImageIcon backgroundFunction = new ImageIcon(getClass().getResource("/image/Logo.png"));
        Image imgBackgroundFunction = backgroundFunction.getImage();
        Image scaledBackgroundFunction = imgBackgroundFunction.getScaledInstance(jLabelBackground.getWidth(), 
                jLabelBackground.getHeight(), Image.SCALE_SMOOTH);
        jLabelBackground.setIcon(new ImageIcon(scaledBackgroundFunction));
    }//GEN-LAST:event_formWindowOpened

    private void jButtonUserManagementMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUserManagementMouseReleased
        UserManagement jPanelUserManagement = new UserManagement(userLogin);
        jPanelLoader.jPanelLoader(jPanelFunction, jPanelUserManagement);
    }//GEN-LAST:event_jButtonUserManagementMouseReleased

    private void jButtonLogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseReleased
        this.dispose();
        AuthFrame authFrame = new AuthFrame();
        authFrame.setVisible(true);
    }//GEN-LAST:event_jButtonLogoutMouseReleased

    private void jButtonTopicManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTopicManagementActionPerformed
        // TODO add your handling code here:
        TopicsManagement jPanelTopicsManagement = new TopicsManagement();
        jPanelLoader.jPanelLoader(jPanelFunction, jPanelTopicsManagement);
    }//GEN-LAST:event_jButtonTopicManagementActionPerformed

    private void jButtonQuestionManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuestionManagementActionPerformed
        // TODO add your handling code here:
        QuestionManagementUI jPanelQuestionManagement = new QuestionManagementUI();
        jPanelLoader.jPanelLoader(jPanelFunction, jPanelQuestionManagement);
    }//GEN-LAST:event_jButtonQuestionManagementActionPerformed

    private void jButtonTestManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestManagementActionPerformed
        // TODO add your handling code here:
        TestManagementUI jPanelTestManagementUI  = new TestManagementUI();
        jPanelLoader.jPanelLoader(jPanelFunction, jPanelTestManagementUI);
    }//GEN-LAST:event_jButtonTestManagementActionPerformed

    private void jButtonExamManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExamManagementActionPerformed
        // TODO add your handling code here:
        ExamManagementUI jPanelExamManagementUI  = new ExamManagementUI();
        jPanelLoader.jPanelLoader(jPanelFunction, jPanelExamManagementUI);
    }//GEN-LAST:event_jButtonExamManagementActionPerformed

    private void jButtonTakeTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTakeTestActionPerformed
        // TODO add your handling code here:
                ExamSelectionUI jPanelExamSelectionUI  = new ExamSelectionUI();
        jPanelLoader.jPanelLoader(jPanelFunction, jPanelExamSelectionUI);
    }//GEN-LAST:event_jButtonTakeTestActionPerformed
                                            
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExamManagement;
    private javax.swing.JButton jButtonInformation;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonQuestionManagement;
    private javax.swing.JButton jButtonStatistical;
    private javax.swing.JButton jButtonTakeTest;
    private javax.swing.JButton jButtonTestManagement;
    private javax.swing.JButton jButtonTopicManagement;
    private javax.swing.JButton jButtonUserManagement;
    private javax.swing.JLabel jLabelAvatar;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelUserFullName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelFunction;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables
}
